kind: "Workflow"
version: "1"

name: "batch-workflow"

trigger:
  triggerType: "GitPushTrigger"
  triggerEventFieldName: "branch"
  triggerEventFieldComparisonOperator: "equals"
  triggerEventFieldComparisonValue: "batch"

modelPipeline:
  type: ReferenceModelPipeline
  ref : "batch_pipeline.yaml"

deployPipeline:
  stages:
    - name: "batch-deploy"
      friendly_name: "Cron Batch Deploy"
      target:
        deploy_time_env_vars:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: deploy-aws-creds
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: deploy-aws-creds
              key: AWS_SECRET_ACCESS_KEY
        type: "batch"
        env: "staging-us-east-1"
        strategy: "replace"
        name: "batch-deploy"
        friendlyName: "Cron Batch Deploy"
        cron_schedule: "* * * * *"
