kind: "Workflow"
version: "1"

name: "master-workflow"

trigger:
  triggerType: "GitMergeRequestTrigger"
  triggerEventFieldName: "baseBranch"
  triggerEventFieldComparisonOperator: "equals"
  triggerEventFieldComparisonValue: "master"

modelPipeline:
  type: ReferenceModelPipeline
  ref : "pipeline.yaml"

deployPipeline:
  stages:
    - name: "prod-deploy"
      friendly_name: "Deploy to Prod"
      target:
        type: "http-api"
        env: "prod-us-east-1"
        strategy: "replace"
        name: "basic-reg"
        friendlyName: "Basic Regression API"

